import type { Product } from "@/types/product";

/** Datos de demostración cuando el API NestJS aún no está disponible */
export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "iphone-15-pro-128gb-titanio",
    name: "iPhone 15 Pro 128GB Titanio",
    brand: "Apple",
    series: "iPhone 15",
    model: "A3101",
    kind: "nuevo",
    colors: ["Titanio natural", "Titanio azul", "Titanio blanco"],
    storageOptionsGb: [128, 256, 512],
    price: 24999,
    currency: "MXN",
    images: ["/placeholder-phone.svg"],
    stock: 4,
    description: "Equipo nuevo sellado con garantía.",
  },
  {
    id: "2",
    slug: "iphone-14-256gb-morado-seminuevo",
    name: "iPhone 14 256GB Morado (seminuevo)",
    brand: "Apple",
    series: "iPhone 14",
    kind: "seminuevo",
    wearGrade: "muy_bueno",
    colors: ["Morado"],
    storageOptionsGb: [256],
    price: 12999,
    compareAtPrice: 15999,
    currency: "MXN",
    images: ["/placeholder-phone.svg"],
    stock: 2,
    description: "Seminuevo con batería saludable y revisión técnica.",
  },
  {
    id: "3",
    slug: "cargador-usb-c-20w",
    name: "Cargador USB-C 20W",
    brand: "Genérico",
    kind: "accesorio",
    colors: ["Blanco"],
    storageOptionsGb: [],
    price: 349,
    currency: "MXN",
    images: ["/placeholder-phone.svg"],
    stock: 40,
  },
];
